// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using Eco.Core.Items;
    using Eco.Core.Utils;
    using Eco.Core.Utils.AtomicAction;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Services;
    using Eco.Shared.Utils;
    using Gameplay.Systems.Tooltip;
    using Eco.Core.Controller;

    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>
    [Serialized]
    [LocDisplayName("Fertilizers")]
    [Ecopedia("Professions", "Farmer", createAsSubPage: true)]
    [RequiresSkill(typeof(FarmerSkill), 0), Tag("Farmer Specialty"), Tier(2)]
    [Tag("Specialty")]
    [Tag("Teachable")]
    public partial class FertilizersSkill : Skill
    {
        public override LocString DisplayDescription { get { return Localizer.DoStr("Adding additional nutrients to the soil can improve farming yield or, if overdone, ruin it. Levels up by crafting related recipes."); } }

        public override void OnLevelUp(User user)
        {
            user.Skillset.AddExperience(typeof(SelfImprovementSkill), 20, Localizer.DoStr("for leveling up another specialization."));
        }


        public static MultiplicativeStrategy MultiplicativeStrategy =
            new MultiplicativeStrategy(new float[] { 
                1,
                1 - 0.2f,
                1 - 0.25f,
                1 - 0.3f,
                1 - 0.35f,
                1 - 0.4f,
                1 - 0.45f,
                1 - 0.5f,
            });
        public override MultiplicativeStrategy MultiStrategy => MultiplicativeStrategy;

        public static AdditiveStrategy AdditiveStrategy =
            new AdditiveStrategy(new float[] { 
                0,
                0.5f,
                0.55f,
                0.6f,
                0.65f,
                0.7f,
                0.75f,
                0.8f,
            });
        public override AdditiveStrategy AddStrategy => AdditiveStrategy;
        public override int MaxLevel { get { return 7; } }
        public override int Tier { get { return 2; } }
    }

    [Serialized]
    [LocDisplayName("Fertilizers Skill Book")]
    [Ecopedia("Items", "Skill Books", createAsSubPage: true)]
    public partial class FertilizersSkillBook : SkillBook<FertilizersSkill, FertilizersSkillScroll> {}

    [Serialized]
    [LocDisplayName("Fertilizers Skill Scroll")]
    public partial class FertilizersSkillScroll : SkillScroll<FertilizersSkill, FertilizersSkillBook> {}


    public partial class FertilizersSkillBookRecipe : RecipeFamily
    {
        public FertilizersSkillBookRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                "Fertilizers",  //noloc
                Localizer.DoStr("Fertilizers Skill Scroll"),
                new List<IngredientElement>
                {
                    new IngredientElement(typeof(AgricultureResearchPaperAdvancedItem), 3, typeof(FarmingSkill)),
                    new IngredientElement("Basic Research", 5, typeof(FarmingSkill)), //noloc
                },
                new List<CraftingElement>
                {
                    new CraftingElement<FertilizersSkillScroll>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.LaborInCalories = CreateLaborInCaloriesValue(600, typeof(FarmingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(FertilizersSkillBookRecipe), 5, typeof(FarmingSkill));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Fertilizers Skill Scroll"), typeof(FertilizersSkillBookRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(ResearchTableObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
