// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Components.Auth;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Economy;
    using Eco.Gameplay.Housing;
    using Eco.Gameplay.Interactions;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Minimap;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Gameplay.Pipes.LiquidComponents;
    using Eco.Gameplay.Pipes.Gases;
    using Eco.Gameplay.Systems.Tooltip;
    using Eco.Shared;
    using Eco.Shared.Math;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;
    using Eco.Shared.Items;
    using Eco.Gameplay.Pipes;
    using Eco.World.Blocks;
    using Eco.Gameplay.Housing.PropertyValues;
    using Eco.Gameplay.Civics.Objects;
    using Eco.Gameplay.Systems.NewTooltip;
    using Eco.Core.Controller;
    using static Eco.Gameplay.Housing.PropertyValues.HomeFurnishingValue;

    [Serialized]
    [RequireComponent(typeof(PropertyAuthComponent))]
    [RequireComponent(typeof(HousingComponent))]
    [RequireComponent(typeof(SolidAttachedSurfaceRequirementComponent))]
    public partial class HewnSoftwoodTableObject : WorldObject, IRepresentsItem
    {
        public virtual Type RepresentedItemType => typeof(HewnSoftwoodTableItem);
        public override LocString DisplayName => Localizer.DoStr("Hewn Softwood Table");
        public override TableTextureMode TableTexture => TableTextureMode.Wood;

        protected override void Initialize()
        {
            this.ModsPreInitialize();
            this.GetComponent<HousingComponent>().HomeValue = HewnSoftwoodTableItem.homeValue;
            this.ModsPostInitialize();
        }

        /// <summary>Hook for mods to customize WorldObject before initialization. You can change housing values here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize WorldObject after initialization.</summary>
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Hewn Softwood Table")]
    [Ecopedia("Housing Objects", "Tables", createAsSubPage: true)]
    [Tag("Housing", 1)]
    [Tag("Hewn Furnishing", 1)]
    public partial class HewnSoftwoodTableItem : WorldObjectItem<HewnSoftwoodTableObject>
    {
        
        public override LocString DisplayDescription => Localizer.DoStr("A large table for placing things on.");


        public override DirectionAxisFlags RequiresSurfaceOnSides { get;} = 0
                    | DirectionAxisFlags.Down
                ;
        public override HomeFurnishingValue HomeValue => homeValue;
        public static readonly HomeFurnishingValue homeValue = new HomeFurnishingValue()
        {
            Category                 = RoomCategory.General,
            HouseValue               = 1,
            TypeForRoomLimit         = Localizer.DoStr("Table"),
            DiminishingReturnPercent = 0.6f
        };

    }

    [RequiresSkill(typeof(CarpentrySkill), 2)]
    [ForceCreateView]
    public partial class HewnSoftwoodTableRecipe : Recipe
    {
        public HewnSoftwoodTableRecipe()
        {
            this.Init(
                "HewnSoftwoodTable",  //noloc
                Localizer.DoStr("Hewn Softwood Table"),
                new List<IngredientElement>
                {
                    new IngredientElement(typeof(SoftwoodHewnLogItem), 15, typeof(CarpentrySkill), typeof(CarpentryLavishResourcesTalent)),
                    new IngredientElement(typeof(SoftwoodBoardItem), 6, typeof(CarpentrySkill), typeof(CarpentryLavishResourcesTalent)),
                },
                new List<CraftingElement>
                {
                    new CraftingElement<HewnSoftwoodTableItem>()
                });
            this.ModsPostInitialize();
            CraftingComponent.AddTagProduct(typeof(CarpentryTableObject), typeof(HewnTableRecipe), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
