// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Core.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;

    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>

    [Serialized]
    [Solid, Wall, Diggable]
    public partial class CrushedMixedRockBlock :
        Block
        , IRepresentsItem
    {
        public virtual Type RepresentedItemType { get { return typeof(CrushedMixedRockItem); } }
    }

    [Serialized]
    [LocDisplayName("Crushed Mixed Rock")]
    [MaxStackSize(10)]
    [Weight(26000)]
    [Ecopedia("Blocks", "Processed Rock", createAsSubPage: true)]
    [Tag("CrushedRock", 1)]
    [Tag("Silica", 1)]
    [Tag("Excavatable", 1)]
    [RequiresTool(typeof(ShovelItem))]
    public partial class CrushedMixedRockItem :
 
    BlockItem<CrushedMixedRockBlock>
    {
        public override LocString DisplayDescription { get { return Localizer.DoStr("A mixture of rocks that can be used in a variety of recipes or simply as landfill."); } }

        public override bool CanStickToWalls { get { return false; } }
    }

}
