// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Sun Butter")]
    [Category("Hidden")]
    [Weight(20)]
    public partial class SunButterItem : FoodItem
    {
        public override LocString DisplayDescription    => Localizer.DoStr("A revolutionary method to aquire butter.");
        
        public override float Calories                  => 200;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 0, Fat = 12, Protein = 0, Vitamins = 0};
    }

}